# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Cache files
      uses: actions/cache@v2.1.4
      with: 
        path: ~/.cache/pip
        key: ${{ runner.os }}-amm-${{ hashFiles('$GITHUB_WORKSPACE/.github/workflows/run_tests.yml') }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Install dependencies
      run: |
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install --upgrade setuptools
        sudo python3 -m pip install pytest pytest-xdist requests contracting flaky pytest-github-actions-annotate-failures pytest-cov
    - name: Test with pytest
      run: |
        cd $GITHUB_WORKSPACE/lamden-version/
        sudo python3 -m pytest test_refactor.py -n 2 --force-flaky --cov=dex_contract --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
